version: "2"
services:
  mysql:
    image: mysql:5.7.12
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=karambacars
    restart: always
    ports:
      - ${EXTERNAL_MYSQL_PORT}:3306
    volumes:
      - ./config/mysql/:/etc/mysql/conf.d
      - /opt/carnovo/${ENVIRONMENT}/db:/var/lib/mysql
  karambacars:
    image: "${DOCKER_REGISTRY}/${BACKEND_PROJECT_NAME}:${KARAMBACARS_VERSION}"
    environment:
      - DB_HOST=mysql
    ports:
      - ${BACKEND_PORT}:80
    volumes:
      - ./config/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./config/symfony/${ENVIRONMENT}/parameters.yml:/var/www/carambacars/app/config/parameters.yml
      - /opt/carnovo/${ENVIRONMENT}/images:/var/www/carambacars/web/images/
      - /opt/carnovo/${ENVIRONMENT}/attachments:/var/www/carambacars/web/attachments/
    depends_on:
      - mysql
    restart: always
    networks:
      default:
        aliases:
          - api.karamba.app
  mailserver:
    image: catatnight/postfix
    environment:
      - maildomain=carnovo.com
      - smtp_user=car:1234
    restart: always
  proxy:
    image: "${DOCKER_REGISTRY}/${PROXY_PROJECT_NAME}:${KARAMBA_FRONTEND_VERSION}"
    restart: always
    ports:
      - ${EXTERNAL_PORT}:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /opt/carnovo/${ENVIRONMENT}/images:/usr/share/nginx/html/images
      - /opt/carnovo/${ENVIRONMENT}/attachments:/usr/share/nginx/html/attachments
  admin:
    image: "${DOCKER_REGISTRY}/${ADMIN_PROJECT_NAME}:${KARAMBA_FRONTEND_VERSION}"
    restart: always
    ports:
      - ${ADMIN_PORT}:80
    networks:
          default:
            aliases:
              - admin.karamba.app
  carnovo:
    image: "${DOCKER_REGISTRY}/${FRONTEND_PROJECT_NAME}:${KARAMBA_FRONTEND_VERSION}"
    restart: always
    ports:
      - ${CARNOVO_PORT}:80
    networks:
          default:
            aliases:
              - carnovo.karamba.app
